### ISSUE TITLE
[FEAT] 마이페이지 UI

### ISSUE THREAD

**Issue by vcz-polly** [IT-Cotato/9th-Growing-Pain-FE#22]
## 🛠️ Description for development features
작업할 사항에 대해 작성해주세요.

## 📝 Todo-lists
- [x] 프로필
    - [x] 일반 정보 편집
    - [x] 자기 소개 편집
- [x] 커뮤니티 활동
- [x] 계정관리

- [x] 알림

**Comment by haydenCho** [comment]
~~커뮤니티 댓글 알림 누르면 해당 페이지로 넘어가는 것 구현해야 함~~ -> 수정완
